print("enter your name:")
name=input()
print("enter your nick name:")
nick_name=input()
print("enter your age:")
age=input()
print("enter your father name:")
father_name=input()
print("enter your mother name:")
mother_name=input()
print("entr your blood group:")
blood_group=input()
print("enter your phone namber:")
phone_namber=input()

print(f"My name is {name}.I have a nick name is {nick_name}.My age is {age}.My father name is {father_name}.My mother name is {mother_name}.My bloos grope is {blood_group}.My phone number is {phone_namber}.")